import 'osi_journey_scenario.dart';

class DefaultOSIScenarios {
  static final OSIScenario defaultHttpScenario = OSIScenario(
    id: 'http_get_default',
    name: 'HTTP Request (PC-A ➔ Server)',
    description: 'PC-A (192.168.1.10) sends an HTTP GET request to Web Server (10.0.0.5) through a Switch and Router.',
    sourceDevice: 'PC-A (192.168.1.10)',
    destinationDevice: 'Server (10.0.0.5)',
    quiz: {
      'question': 'What happens to the Layer 3 IP Header when the packet passes through the Router?',
      'options': [
        'The Destination IP changes to the Router IP',
        'The TTL (Time To Live) is decremented by 1 (64 ➔ 63) while Source & Dest IP remain unchanged',
        'The Source IP is replaced by the MAC address',
        'Layer 3 headers are stripped and not forwarded'
      ],
      'correctIndex': 1,
      'explanation': 'Routers operate at Layer 3. They decrement the IP header TTL (Time To Live) by 1 to prevent routing loops, while maintaining original end-to-end Source & Dest IP addresses.',
      'xpReward': 50,
    },
    steps: [
      // --- ENCAPSULATION AT PC-A (L7 down to L1) ---
      const OSIStep(
        stepIndex: 0,
        title: 'Layer 7 — Application Encapsulation',
        phase: 'encapsulation',
        activeSenderLayer: 7,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.0,
        caption: 'Layer 7: The web browser on PC-A generates an HTTP GET request payload for web page data.',
        deviceHighlight: 'Generating HTTP Request Payload',
        headerFields: [
          OSIHeaderField(name: 'Application Protocol', value: 'HTTP / 1.1'),
          OSIHeaderField(name: 'HTTP Method', value: 'GET /index.html'),
          OSIHeaderField(name: 'Host Header', value: '10.0.0.5'),
          OSIHeaderField(name: 'Payload Size', value: '32 Bytes (Plaintext)'),
        ],
      ),
      const OSIStep(
        stepIndex: 1,
        title: 'Layer 6 — Presentation Formatting',
        phase: 'encapsulation',
        activeSenderLayer: 6,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.05,
        caption: 'Layer 6: Data is formatted using UTF-8 encoding and prepared for optional TLS/SSL encryption.',
        deviceHighlight: 'Encoding Data to Standard Format',
        headerFields: [
          OSIHeaderField(name: 'Encoding Format', value: 'UTF-8 Plaintext'),
          OSIHeaderField(name: 'Data Compression', value: 'Disabled'),
          OSIHeaderField(name: 'TLS Status', value: 'Plaintext (HTTP)'),
        ],
      ),
      const OSIStep(
        stepIndex: 2,
        title: 'Layer 5 — Session Establishment',
        phase: 'encapsulation',
        activeSenderLayer: 5,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.1,
        caption: 'Layer 5: Session parameters are established to manage full-duplex dialog with Server.',
        deviceHighlight: 'Assigning Session Identifier',
        headerFields: [
          OSIHeaderField(name: 'Session ID', value: '0x9A4B12C0'),
          OSIHeaderField(name: 'Dialog Mode', value: 'Full-Duplex Sync'),
          OSIHeaderField(name: 'Connection State', value: 'ESTABLISHED'),
        ],
      ),
      const OSIStep(
        stepIndex: 3,
        title: 'Layer 4 — Transport Encapsulation',
        phase: 'encapsulation',
        activeSenderLayer: 4,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.15,
        caption: 'Layer 4: TCP encapsulates the data into a Segment, attaching ephemeral Source Port 54321 and Destination Port 80.',
        deviceHighlight: 'Adding TCP Transport Header',
        headerFields: [
          OSIHeaderField(name: 'Transport Protocol', value: 'TCP'),
          OSIHeaderField(name: 'Source Port', value: '54321 (Ephemeral)'),
          OSIHeaderField(name: 'Destination Port', value: '80 (HTTP)'),
          OSIHeaderField(name: 'Sequence Number', value: '1001'),
          OSIHeaderField(name: 'TCP Checksum', value: '0x4E1A (Valid)'),
        ],
      ),
      const OSIStep(
        stepIndex: 4,
        title: 'Layer 3 — Network Encapsulation',
        phase: 'encapsulation',
        activeSenderLayer: 3,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.2,
        caption: 'Layer 3: IP encapsulates the Segment into a Packet, setting Source IP 192.168.1.10, Dest IP 10.0.0.5, and TTL 64.',
        deviceHighlight: 'Adding IP Logical Header',
        headerFields: [
          OSIHeaderField(name: 'Network Protocol', value: 'IPv4'),
          OSIHeaderField(name: 'Source IP', value: '192.168.1.10'),
          OSIHeaderField(name: 'Destination IP', value: '10.0.0.5'),
          OSIHeaderField(name: 'Time To Live (TTL)', value: '64 Hops'),
          OSIHeaderField(name: 'IP Header Checksum', value: '0x9B8C'),
        ],
      ),
      const OSIStep(
        stepIndex: 5,
        title: 'Layer 2 — Data Link Framing',
        phase: 'encapsulation',
        activeSenderLayer: 2,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.25,
        caption: 'Layer 2: Ethernet II encapsulates the Packet into a Frame, attaching PC-A Source MAC and Gateway Router Destination MAC.',
        deviceHighlight: 'Adding Ethernet MAC Header & FCS',
        headerFields: [
          OSIHeaderField(name: 'Frame Format', value: 'Ethernet II'),
          OSIHeaderField(name: 'Source MAC', value: 'AA:AA:AA:11:11:11 (PC-A)'),
          OSIHeaderField(name: 'Destination MAC', value: 'GW:GW:GW:00:00:01 (Router Eth0)'),
          OSIHeaderField(name: 'EtherType', value: '0x0800 (IPv4 Payload)'),
          OSIHeaderField(name: 'FCS / CRC', value: '0x7B1C904E'),
        ],
      ),
      const OSIStep(
        stepIndex: 6,
        title: 'Layer 1 — Physical Bit Transmission',
        phase: 'encapsulation',
        activeSenderLayer: 1,
        activeReceiverLayer: 0,
        activeDevice: 'PC-A',
        pathProgress: 0.3,
        caption: 'Layer 1: The binary frame is converted into electrical voltage pulses transmitted across the RJ-45 cable.',
        deviceHighlight: 'Pulsing Bits onto Copper Wire',
        bitstream: '01001001 01000011 01001101 01010000 01010011',
        headerFields: [
          OSIHeaderField(name: 'Physical Medium', value: 'Copper Cat6 RJ-45 Cable'),
          OSIHeaderField(name: 'Signal Encoding', value: 'NRZ Electrical Voltage Pulses'),
          OSIHeaderField(name: 'Link Speed', value: '1 Gbps Full-Duplex'),
        ],
      ),

      // --- TRANSIT AT SWITCH & ROUTER ---
      const OSIStep(
        stepIndex: 7,
        title: 'Switch Transit — Layer 2 MAC Forwarding',
        phase: 'transit',
        activeSenderLayer: 0,
        activeReceiverLayer: 0,
        activeDevice: 'Switch',
        pathProgress: 0.45,
        caption: 'Switch (Layer 2): Inspects Destination MAC (GW:GW:GW:00:00:01), checks its MAC Address Table, and forwards frame toward Router.',
        deviceHighlight: 'Inspecting Layer 2 MAC Table (Unchanged IP/TCP headers)',
        headerFields: [
          OSIHeaderField(name: 'Switch Operating Level', value: 'Layer 2 (Data Link Only)'),
          OSIHeaderField(name: 'MAC Table Match', value: 'Port 2 ➔ Router Gateway'),
          OSIHeaderField(name: 'Source MAC', value: 'AA:AA:AA:11:11:11'),
          OSIHeaderField(name: 'Destination MAC', value: 'GW:GW:GW:00:00:01'),
          OSIHeaderField(name: 'Source IP', value: '192.168.1.10'),
          OSIHeaderField(name: 'Destination IP', value: '10.0.0.5'),
          OSIHeaderField(name: 'TTL', value: '64 (Unchanged by Switch)'),
        ],
      ),
      const OSIStep(
        stepIndex: 8,
        title: 'Router Transit — Layer 3 Routing & MAC Rewrite',
        phase: 'transit',
        activeSenderLayer: 0,
        activeReceiverLayer: 0,
        activeDevice: 'Router',
        pathProgress: 0.65,
        caption: 'Router (Layer 3): Inspects Dest IP 10.0.0.5, decrements TTL (64 ➔ 63), and rewrites Layer 2 MAC header for Server subnet forwarding.',
        deviceHighlight: 'Routing Table Lookup & Layer 2 Header Rewrite',
        headerFields: [
          OSIHeaderField(name: 'Router Operating Level', value: 'Layer 3 (Network Routing)'),
          OSIHeaderField(name: 'Routing Decision', value: 'Route 10.0.0.0/24 ➔ Eth1 Direct'),
          OSIHeaderField(name: 'Time To Live (TTL)', value: '63 Hops', isChanged: true, previousValue: '64 Hops', explanation: 'TTL decremented by 1 at router hop'),
          OSIHeaderField(name: 'Source MAC', value: 'GW:GW:GW:00:00:02 (Router Eth1)', isChanged: true, previousValue: 'AA:AA:AA:11:11:11 (PC-A)', explanation: 'Layer 2 MAC rewritten for next hop link'),
          OSIHeaderField(name: 'Destination MAC', value: 'BB:BB:BB:22:22:22 (Server NIC)', isChanged: true, previousValue: 'GW:GW:GW:00:00:01 (Router Eth0)', explanation: 'Target server MAC inserted'),
          OSIHeaderField(name: 'Source IP', value: '192.168.1.10 (Unchanged)', isChanged: false),
          OSIHeaderField(name: 'Destination IP', value: '10.0.0.5 (Unchanged)', isChanged: false),
        ],
      ),

      // --- DECAPSULATION AT SERVER (L1 up to L7) ---
      const OSIStep(
        stepIndex: 9,
        title: 'Layer 1 — Physical Bit Reception',
        phase: 'decapsulation',
        activeSenderLayer: 0,
        activeReceiverLayer: 1,
        activeDevice: 'Server',
        pathProgress: 0.85,
        caption: 'Layer 1: Server network interface card (NIC) receives bitstream signals from physical cable.',
        deviceHighlight: 'Demodulating Cable Voltage Signals',
        bitstream: '01001001 01000011 01001101 01010000 01010011',
        headerFields: [
          OSIHeaderField(name: 'Physical NIC', value: 'Gigabit Ethernet eth0'),
          OSIHeaderField(name: 'Signal Status', value: 'Bitstream Synced & Clocked'),
        ],
      ),
      const OSIStep(
        stepIndex: 10,
        title: 'Layer 2 — Data Link Decapsulation',
        phase: 'decapsulation',
        activeSenderLayer: 0,
        activeReceiverLayer: 2,
        activeDevice: 'Server',
        pathProgress: 0.88,
        caption: 'Layer 2: Server verifies Destination MAC matches BB:BB:BB:22:22:22, validates FCS checksum, and strips Ethernet header.',
        deviceHighlight: 'Stripping Layer 2 Frame Header',
        headerFields: [
          OSIHeaderField(name: 'Matched Dest MAC', value: 'BB:BB:BB:22:22:22 (Server MAC)'),
          OSIHeaderField(name: 'FCS Verification', value: '0x7B1C904E (Frame OK)'),
          OSIHeaderField(name: 'Action', value: 'Strip L2 Ethernet Header ➔ Pass Packet Up to L3'),
        ],
      ),
      const OSIStep(
        stepIndex: 11,
        title: 'Layer 3 — Network Decapsulation',
        phase: 'decapsulation',
        activeSenderLayer: 0,
        activeReceiverLayer: 3,
        activeDevice: 'Server',
        pathProgress: 0.91,
        caption: 'Layer 3: IP layer verifies Destination IP 10.0.0.5 matches local IP and strips the IP header.',
        deviceHighlight: 'Stripping Layer 3 IP Header',
        headerFields: [
          OSIHeaderField(name: 'Verified Dest IP', value: '10.0.0.5 (Local Server IP)'),
          OSIHeaderField(name: 'Received TTL', value: '63 Hops (Valid)'),
          OSIHeaderField(name: 'Action', value: 'Strip L3 IP Header ➔ Pass Segment Up to L4'),
        ],
      ),
      const OSIStep(
        stepIndex: 12,
        title: 'Layer 4 — Transport Decapsulation',
        phase: 'decapsulation',
        activeSenderLayer: 0,
        activeReceiverLayer: 4,
        activeDevice: 'Server',
        pathProgress: 0.94,
        caption: 'Layer 4: TCP verifies Destination Port 80, reassembles segment order, and delivers payload to HTTP service process.',
        deviceHighlight: 'Stripping Layer 4 TCP Header',
        headerFields: [
          OSIHeaderField(name: 'Target Port', value: '80 (HTTP Server)'),
          OSIHeaderField(name: 'Seq / Ack Verified', value: 'Seq 1001 Validated'),
          OSIHeaderField(name: 'Action', value: 'Strip L4 TCP Header ➔ Deliver Data Payload Up to L5-L7'),
        ],
      ),
      const OSIStep(
        stepIndex: 13,
        title: 'Layer 5–7 — Application Delivery Delivered!',
        phase: 'decapsulation',
        activeSenderLayer: 0,
        activeReceiverLayer: 7,
        activeDevice: 'Server',
        pathProgress: 1.0,
        caption: 'Layer 7: HTTP GET request payload delivered successfully to Server web application process!',
        deviceHighlight: 'HTTP GET Request Delivered to Web Server Application',
        headerFields: [
          OSIHeaderField(name: 'Received Request', value: 'HTTP GET /index.html'),
          OSIHeaderField(name: 'Web Server Action', value: 'HTTP 200 OK Response Prepared'),
          OSIHeaderField(name: 'OSI Journey Status', value: 'Complete Encapsulation ➔ Transit ➔ Decapsulation Cycle Finished!'),
        ],
      ),
    ],
  );
}
